### ISSUE TITLE
Docker images throw error for inference

### ISSUE THREAD

**Issue by michaelroyzen** [ruotianluo/GoogleConceptualCaptioning#6]
I tried running both Docker images as described and got the same error each time. From the conceptual-captions directory, I ran `python /conceptual-captions/generate_caption.py test_images.txt test_images/ my_output.txt`. My hardware is 2x 2080 Ti (11G VRAM), but I also ran it on Tesla T4 (16G VRAM) on another system and received the same error.

It resulted in this error:
`F0228 00:44:42.409458    41 cudnn_conv_layer.cu:28] Check failed: status == CUDNN_STATUS_SUCCESS (8 vs. 0)  CUDNN_STATUS_EXECUTION_FAILED
*** Check failure stack trace: ***
    @     0x7f3f56f2e5cd  google::LogMessage::Fail()
    @     0x7f3f56f30433  google::LogMessage::SendToLog()
    @     0x7f3f56f2e15b  google::LogMessage::Flush()
    @     0x7f3f56f30e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3f578d3c83  caffe::CuDNNConvolutionLayer<>::Forward_gpu()
    @     0x7f3f5784abb1  caffe::Net<>::ForwardFromTo()
    @     0x7f3f583822bb  boost::python::objects::caller_py_function_impl<>::operator()()
    @     0x7f3f5737f5cd  boost::python::objects::function::call()
    @     0x7f3f5737f7c8  (unknown)
    @     0x7f3f57387613  boost::python::handle_exception_impl()
    @     0x7f3f5737c999  (unknown)
    @     0x7f3f66878b73  (unknown)
    @     0x7f3f6690f119  PyType_Ready
    @     0x7f3f66914a99  best_base
    @     0x7f3f6689d7c7  (unknown)
    @     0x7f3f66878b73  (unknown)
    @     0x7f3f6690da6e  PyType_Modified
    @     0x7f3f66914a99  best_base
    @     0x7f3f66911f68  slot_tp_repr
    @     0x7f3f66914a99  best_base
    @     0x7f3f66911f68  slot_tp_repr
    @     0x7f3f6691354e  slot_nb_xor
    @     0x7f3f66914a99  best_base
    @     0x7f3f66914cba  type_new
    @     0x7f3f6692e01d  _PyUnicodeUCS4_ToNumeric
    @     0x7f3f6692f1c8  _PyUnicodeUCS4_ToNumeric
    @     0x7f3f669303e8  warn_explicit
    @     0x7f3f6694267c  ast_for_comprehension
    @     0x7f3f65b13830  __libc_start_main
    @     0x55fdf1f4507f  (unknown)
Aborted (core dumped)
mv: cannot stat 'feats_att': No such file or directory
mv: cannot stat 'feats_fc': No such file or directory
mv: cannot stat 'feats_box': No such file or directory
/opt/conda/lib/python2.7/site-packages/smart_open/ssh.py:34: UserWarning: paramiko missing, opening SSH/SCP/SFTP paths will be disabled.  `pip install paramiko` to suppress
  warnings.warn('paramiko missing, opening SSH/SCP/SFTP paths will be disabled.  `pip install paramiko` to suppress')
DataLoader loading json file:  testdata/testtalk.json
DataLoader loading h5 file:  testdata/feats_fc testdata/feats_att testdata/feats_box none
read 18 image features
assigned 18 images to split train
assigned 18 images to split val
assigned 18 images to split test
Traceback (most recent call last):
  File "eval_ensemble.py", line 96, in <module>
    vars(opt))
  File "/conceptual-captions/captioning/eval_utils.py", line 123, in eval_split
    data = loader.get_batch(split)
  File "/conceptual-captions/captioning/dataloader.py", line 219, in get_batch
    ix, tmp_wrapped = self._prefetch_process[split].get()
  File "/conceptual-captions/captioning/dataloader.py", line 425, in get
    tmp = self.split_loader.next()
  File "/opt/conda/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/conceptual-captions/captioning/dataloader.py", line 318, in __getitem__
    att_feat = self.att_loader.get(str(self.info['images'][ix]['id']))
  File "/conceptual-captions/captioning/dataloader.py", line 56, in get
    feat = self.loader(f_input)
  File "/conceptual-captions/captioning/dataloader.py", line 31, in <lambda>
    self.loader = lambda x: np.load(x)['feat']
  File "/opt/conda/lib/python2.7/site-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'testdata/feats_att/0006400c1c224e19.jpg.npz'

Terminating BlobFetcher`

Please let me know how I can fix this error. Thanks!

**Comment by michaelroyzen** [comment]
The docker images and instructions provided in the README seem to be broken @ruotianluo. It would be awesome if you could chime in on this. Thanks!

**Comment by ruotianluo** [comment]
It's the feature extraction broken. I ran it on 1080ti. Can you try lower compute compatibility machines?

**Comment by michaelroyzen** [comment]
Unfortunately, I don't have access to those. What makes this project incompatible with capability 7.5 devices, and what can be done to fix it?

**Comment by ruotianluo** [comment]
the bottom up attention(caffe) I built in the docker doesn't support 7.5 (that's my guess)

**Comment by michaelroyzen** [comment]
Thanks. Could you please give instructions on how to recompile Caffe for compute 7.5? @ruotianluo

**Comment by ruotianluo** [comment]
```
FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04 

RUN echo "deb http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list

RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         git \
         curl \
         vim \
         ca-certificates \         
         libjpeg-dev \
         libpng-dev &&\
     rm -rf /var/lib/apt/lists/*

##########################################
# Install anaconda2

RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion

RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/archive/Anaconda2-5.0.1-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh

ENV PATH /opt/conda/bin:$PATH

##########################################
# Install java

RUN apt-get update && apt-get install -y --no-install-recommends \
    default-jre \
    default-jdk

#########################################
# Install caffe necessary stuff

RUN apt-get install -y libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler
RUN apt-get install -y --no-install-recommends libboost-all-dev

RUN apt-get install -y \
        libatlas-base-dev \
        libgflags-dev \
        libgoogle-glog-dev \
        liblmdb-dev

RUN apt-get install -y libnccl2=2.4.2-1+cuda10.0 libnccl-dev=2.4.2-1+cuda10.0

########################################
# Install easydict opencv
RUN pip install easydict
RUN conda install -y opencv

# Install protobuf
RUN pip install protobuf

########################################
# Install bottom-up
RUN git clone https://80da400d080b33ffcf6933fd7c6d6fb24bf36b28@github.com/ruotianluo/bottom-up-attention-conceptual
RUN cd bottom-up-attention-conceptual/caffe/ && \
  mkdir build && cd build && cmake -DCUDA_ARCH_NAME=Manual -DCUDA_ARCH_BIN="30 35 50 60 61 70 75" -DCMAKE_CXX_STANDARD=11  .. && make all; make all && make install && \
  cd ../../../
RUN cd bottom-up-attention-conceptual/lib && make && cd ../../


############################3
# Install pytorch

RUN conda install pytorch torchvision cudatoolkit=10.0 -c pytorch

###########################
# Download bottom-up pretrained wieghts
RUN cd bottom-up-attention-conceptual/ && cd data && mkdir faster_rcnn_models && cd faster_rcnn_models && wget https://storage.googleapis.com/bottom-up-attention/resnet101_faster_rcnn_final.caffemodel && cd ../../../

##################################
# Install pudb
RUN pip install pudb

################################
# reinstlal h5py
RUN conda remove --force  hdf5
RUN conda install hdf5==1.10.1

RUN pip install lmdb

################################
# add code
RUN head -c 5 /dev/random > random_byte
ADD conceptual-captions /conceptual-captions/
#RUN cd conceptual-captions/ 
# copy models
# copy models
 
WORKDIR /workspace
RUN chmod -R a+w /workspace

```

This is the dockerfile to build the image. It seems it should be compatible with compute 7.5. You can build yourself to see if it works.

**Comment by nbcmguarin0** [comment]
the Dockerfile provided above throws this error for me `The command '/bin/sh -c apt-get install -y libnccl2=2.4.2-1+cuda10.0 libnccl-dev=2.4.2-1+cuda10.0' returned a non-zero code: 100` did this issue find a resolution?

**Comment by Sonaliam** [comment]
Dear Google team,
Please help me to solve the following error.
I want to use this program only for inference.

I am running the docker image with the following command:
python /conceptual-captions/generate_caption.py test_images/0006400c1c224e19.jpg test_images test_images/11.jpg
**I am getting a following error:** : **UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte**

Traceback (most recent call last):
  File "detect_image_list.py", line 194, in <module>
    generate_tsv(0, args.prototxt, args.caffemodel, args.im_base_file, args.im_dir)      
  File "detect_image_list.py", line 168, in generate_tsv
    writer.writerow(get_detections_from_im(net, os.path.join(im_dir, im_file)))
  File "detect_image_list.py", line 51, in get_detections_from_im
    scores, boxes, attr_scores, rel_scores = im_detect(net, im)
  File "/bottom-up-attention-conceptual/tools/../lib/fast_rcnn/test.py", line 123, in im_detect
    blobs, im_scales = _get_blobs(im, boxes)
  File "/bottom-up-attention-conceptual/tools/../lib/fast_rcnn/test.py", line 104, in _get_blobs
    blobs['data'], im_scale_factors = _get_image_blob(im)
  File "/bottom-up-attention-conceptual/tools/../lib/fast_rcnn/test.py", line 34, in _get_image_blob
    im_orig = im.astype(np.float32, copy=True)
AttributeError: 'NoneType' object has no attribute 'astype'
Traceback (most recent call last):
  File "/conceptual-captions/generate_caption.py", line 24, in <module>
    json.dump(testtalk, open('captioning/testdata/testtalk.json', 'w'))
  File "/opt/conda/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/opt/conda/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/opt/conda/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/opt/conda/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/opt/conda/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
**UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte**
